r buildvrt.gdal: Create GDAL VRTs for GDAL linked raster maps
OSGeo/grass-addons pull request #1209
Opened 2024-09-21 23:30 UTC by ninsbl

A workaround for https://github.com/OSGeo/grass/issues/4345

2024-09-22 02:06 UTC, wenzeslaus requested changes
This looks great. Thanks for sharing it. I have some minor comments.

2024-09-22 02:06 UTC, wenzeslaus commented on src/raster/r.buildvrt.gdal/r.buildvrt.gdal.html
> +directory named "gdal" in the current mapset og in a userdefined <b>
```suggestion
directory named "gdal" in the current mapset or in a user-defined <b>
```

2024-09-22 02:06 UTC, wenzeslaus commented on src/raster/r.buildvrt.gdal/r.buildvrt.gdal.py
> +            )["input"]
Please look at https://github.com/OSGeo/grass/pull/4216 whether that would help here.

2024-09-22 02:06 UTC, wenzeslaus commented on src/raster/r.buildvrt.gdal/r.buildvrt.gdal.py
> +        # Check if Path can be read from command history
Don't use capital letter for Path and instead say which path that is. This is probably the most fragile part of the code in terms of relying on other things to be in place.

2024-09-22 02:06 UTC, wenzeslaus commented on src/raster/r.buildvrt.gdal/r.buildvrt.gdal.py
> +                gs.parse_key_val(header_path.read_text().replace(": ", "="))["file"]
Would the following work?

```suggestion
                gs.parse_key_val(header_path.read_text(), sep=": "))["file"]
```

2024-09-22 02:06 UTC, wenzeslaus commented on src/raster/r.buildvrt.gdal/r.buildvrt.gdal.py
> +        return gdal_path
I'm not sure how to handle that, but I did hit this issue in the past. It seems we should have API to make usage of GRASS Driver easier. Perhaps spit a GDAL-compatible path out in r.info output?

2024-09-22 02:06 UTC, wenzeslaus commented on src/raster/r.buildvrt.gdal/r.buildvrt.gdal.py
> +        )
Given that you are using gdal only in the _main_ function, moving this to _main_ should be easy and you will avoid warnings about options and flags being on the top-level.

2024-09-22 02:06 UTC, wenzeslaus commented on src/raster/r.buildvrt.gdal/r.buildvrt.gdal.py
> +        overwrite=gs.overwrite(),
This should be automatic.

2024-09-22 11:06 UTC, neteler commented on src/raster/r.buildvrt.gdal/r.buildvrt.gdal.html
> +<a href="https://grass.osgeo.org/grass-stable/manuals/r.external.out.html">r.external.out</a>,
```suggestion
time r.univar map=vrt_${format_type}_gdal
</pre></div>

<h2>SEE ALSO</h2>
<em>
<a href="https://grass.osgeo.org/grass-stable/manuals/r.buildvrt.html">r.buildvrt</a>,
<a href="https://grass.osgeo.org/grass-stable/manuals/r.patch.html">r.patch</a>,
<a href="https://grass.osgeo.org/grass-stable/manuals/r.external.html">r.external</a>,
<a href="https://grass.osgeo.org/grass-stable/manuals/r.external.out.html">r.external.out</a>
```

2024-09-22 20:55 UTC, ninsbl commented on src/raster/r.buildvrt.gdal/r.buildvrt.gdal.py
> +        return gdal_path
Sounds good.

2024-09-22 21:35 UTC, ninsbl commented on src/raster/r.buildvrt.gdal/r.buildvrt.gdal.py
> +        )
Implemented in [bd4e206](https://github.com/OSGeo/grass-addons/pull/1209/commits/bd4e2061a73f6acf4d5f314abdb7cd7112da8088)

2024-09-22 21:36 UTC, ninsbl commented on src/raster/r.buildvrt.gdal/r.buildvrt.gdal.py
> +            )["input"]
JSON output now used in [bd4e206](https://github.com/OSGeo/grass-addons/pull/1209/commits/bd4e2061a73f6acf4d5f314abdb7cd7112da8088)

2024-09-22 21:39 UTC, ninsbl commented on src/raster/r.buildvrt.gdal/r.buildvrt.gdal.py
> +        # Check if Path can be read from command history
Indeed. This is what I started with when I tried to get the GDAL-path of a linked dataset, but I am not 100% this is reached in normal cases of GDAL-linked data. So we may remove it...

2024-09-22 21:45 UTC, ninsbl commented on src/raster/r.buildvrt.gdal/r.buildvrt.gdal.py
> +        overwrite=gs.overwrite(),
Addressed in [bd4e206](https://github.com/OSGeo/grass-addons/pull/1209/commits/bd4e2061a73f6acf4d5f314abdb7cd7112da8088)

2024-09-23 07:00 UTC, ninsbl commented
The requested changes should be addressed.

2024-09-23 12:35 UTC, wenzeslaus commented on src/raster/r.buildvrt.gdal/r.buildvrt.gdal.py
> +        return gdal_path
Would you mind opening an issue for this?

2024-09-23 12:42 UTC, wenzeslaus approved these changes

2024-09-23 12:45 UTC, wenzeslaus commented on src/raster/r.buildvrt.gdal/r.buildvrt.gdal.py
> +        # Check if Path can be read from command history
True, I think if the gdal header information is missing, then there is really a big problem and the data can't be actually read, so you can remove it without loosing any functionality.

2024-09-23 21:16 UTC, ninsbl commented on src/raster/r.buildvrt.gdal/r.buildvrt.gdal.py
> +        # Check if Path can be read from command history
Removed in [ea2a29d](https://github.com/OSGeo/grass-addons/pull/1209/commits/ea2a29ddcde6073d00dfa0817852e44733ab8a3e)

2024-09-23 21:52 UTC, merged