PEP8: fix flake8 errors
OSGeo/grass-addons pull request #290
Opened 2020-09-28 09:45 UTC by neteler

This PR fixes PEP8 errors identified with flake8 and selectively fixed with autopep8.

For easier review, the different errors and warnings are separate out into single commits.

2020-09-28 09:48 UTC, neteler commented
Leftover are:

- 4 x   F403 'from mdlib.cswutil import *' used; unable to detect undefined names
- 33 x F405 'open_url' may be undefined, or defined from star imports: .cswutil
- 1 x    F632 use ==/!= to compare constant literals (str, bytes, int, float, tuple)
- 2 x    F811 redefinition of unused 'CatalogueServiceWeb' from line 18

My test script:

```
cat ~/bin/qa_run_flake8.sh 
#!/bin/sh

# Markus Neteler, 2020
# script to recursively check GRASS GIS Python scripts for selected PEP8 errors

# Fedora: sudo pip3 install flake8 flake8-colors 
# Ubuntu: pip3 install flake8 flake8-colors

# fetch/update GRASS GIS optimized config
wget --quiet https://raw.githubusercontent.com/OSGeo/grass/master/scripts/.flake8 -O .flake8
echo 'format = ${cyan}%(path)s${reset}:${yellow_bold}%(row)d${reset}:${green_bold}%(col)d${reset}: ${red_bold}%(code)s${reset} %(text)s' >> .flake8

# run flake8 on directory tree
flake8 --count --statistics --show-source --jobs=4 .

rm -f .flake8
```

2020-09-29 20:42 UTC, tmszi requested changes

2020-09-29 20:42 UTC, tmszi commented on grass7/gui/wxpython/wx.metadata/g.gui.metadata/g.gui.metadata.py
> +            GError('Initialize of temporal tree catalogue error: < %s >' %e)
```suggestion
            GError('Initialize of temporal tree catalogue error: < %s >' % e)
```

2020-09-29 20:42 UTC, tmszi commented on grass7/gui/wxpython/wx.metadata/mdlib/mdeditorfactory.py
> +            print("WARNING: Cannot check and remove non ascii characters from template err:< %s >" %err)
```suggestion
            print("WARNING: Cannot check and remove non ascii characters from template err:< %s >" % err)
```

2020-09-29 20:42 UTC, tmszi commented on grass7/gui/wxpython/wx.metadata/mdlib/mdeditorfactory.py
> +        self.keysList=wx.TreeCtrl(parent=self.parent, id=ID_ANY,size=(0, 120),style=wx.TR_FULL_ROW_HIGHLIGHT |wx.TR_DEFAULT_STYLE)
```suggestion
        self.keysList=wx.TreeCtrl(parent=self.parent, id=ID_ANY, size=(0, 120), style=wx.TR_FULL_ROW_HIGHLIGHT | wx.TR_DEFAULT_STYLE)
```

2020-09-29 20:42 UTC, tmszi commented on grass7/gui/wxpython/wx.metadata/mdlib/mdgrass.py
> +            grass.message('GDAL python library is not installed: %s \n identifying of EPSG is disabled' %e)
```suggestion
            grass.message('GDAL python library is not installed: %s \n identifying of EPSG is disabled' % e)
```

2020-09-29 20:42 UTC, tmszi commented on grass7/gui/wxpython/wx.metadata/mdlib/mdgrass.py
> +            self.md.referencesystem.code='http://www.opengis.net/def/crs/EPSG/0/%s' %epsg
```suggestion
            self.md.referencesystem.code = 'http://www.opengis.net/def/crs/EPSG/0/%s' % epsg
```

2020-09-29 21:17 UTC, neteler commented
Thanks, @tmszi !

2020-09-29 21:19 UTC, neteler commented
The open issues as per https://github.com/OSGeo/grass-addons/pull/290#issuecomment-699902744 might be addressed in separate PR(s).

If you agree, I'd merge this PR now.

2020-09-30 03:50 UTC, tmszi approved these changes

2020-09-30 03:52 UTC, tmszi commented
> Thanks, @tmszi !

You are welcome.

2020-09-30 03:53 UTC, tmszi commented
> The open issues as per [#290 (comment)](https://github.com/OSGeo/grass-addons/pull/290#issuecomment-699902744) might be addressed in separate PR(s).

I will try to look at it today.

> If you agree, I'd merge this PR now.

Yes I agree.

2020-09-30 04:42 UTC, merged