added new addons to calculate vegetation indices from temporal datasets
OSGeo/grass-addons pull request #641
Opened 2021-12-09 08:59 UTC by lucadelu

There is a problem with ParallelModuleQueue, it run the first MultiModule but after that it stop and it remain appended. Is there any suggestions?

2022-01-02 20:46 UTC, ninsbl commented
The MultiModule issue is fixed in GRASS GIS 8.0. See: 
- https://github.com/OSGeo/grass/pull/1407 and
- https://lists.osgeo.org/pipermail/grass-dev/2021-May/095186.html

It has not (yet) been backported to 7.8 though due to a small API change... If this is needed in 7.8, maybe make a backport PR (direct backporting is probably not possible)?

2026-07-12 12:23 UTC, echoix requested changes
Will need a .md file now

2026-07-12 22:08 UTC, neteler commented
> Will need a .md file now

For this, see
https://github.com/OSGeo/grass/blob/main/utils/grass_html2md.sh

2026-07-15 14:33 UTC, veroandreo approved these changes
I fixed a minor thing in the manual only. Tests run and the results are fine.

2026-07-15 20:59 UTC, petrasovaa requested changes
If I remember seeing @veroandreo running the tests, they take too much time, I suggest reducing the number of maps to minimum. Also random maps theoretically take more time to create, single value maps here will work as well.

2026-07-16 02:49 UTC, Deniwn22 reviewed
Tested locally and it works. Consider extracting the retry logic into a shared utility — we have similar code in the auth module.

2026-07-17 08:18 UTC, neteler commented on src/temporal/t.rast.vi/t.rast.vi.html
> +-->
```suggestion
```

2026-07-17 13:53 UTC, echoix requested changes
Little differences in md <-> html

2026-07-17 13:53 UTC, echoix commented on src/temporal/t.rast.vi/t.rast.vi.html
> +```
Empty markdown example in HTML

2026-07-17 13:53 UTC, echoix commented on src/temporal/t.rast.vi/t.rast.vi.html
> +need to set the correct parameters.
Different text than md. Missing ", such as", and the plural of index.

2026-07-17 13:53 UTC, echoix commented on src/temporal/t.rast.vi/t.rast.vi.html
> +</div>
The markdown example has `viname=ndvi` after `output=ndvi_monthly`

2026-07-17 14:09 UTC, echoix approved these changes

2026-07-17 16:15 UTC, petrasovaa approved these changes

2026-07-17 16:23 UTC, merged