v.db.pyupdate: fix to use latest v.db.select format=json option
OSGeo/grass-addons pull request #810
Opened 2022-10-06 02:59 UTC by petrasovaa

At one point during development v.db.select used -j flag for json output, but it was changed to format=json before release. v.db.pyupdate was using the old syntax. Tests are also updated, so they should run now.

2022-10-06 20:40 UTC, ninsbl approved these changes
Test passes. Looks good.

2022-10-06 23:48 UTC, wenzeslaus requested changes
Just delete of one line is needed (comment for now-fixed code).

2022-10-06 23:48 UTC, wenzeslaus commented on src/vector/v.db.pyupdate/v.db.pyupdate.py
>          # TODO: XXX is a workaround for a bug in v.db.select -j
Can be removed.

2022-10-07 03:08 UTC, wenzeslaus approved these changes
Thanks!

2022-10-07 03:21 UTC, merged