v.move.points: Move points by values from raster map
OSGeo/grass-addons pull request #877
Opened 2023-03-17 21:26 UTC by wenzeslaus

WIP code for move of vector features positions by X and Y values given in two raster maps. This can move linear features without breaking the visual connection as points falling into the same raster cell are shifted by the same value.

Alternative name would be v.rast.move because the big deal is that it is using raster to do the moving.

The one example included now shows the principle, moves in X direction both ways depending on the raster values. My use case is randomizing a set of lines (connected and not connected).

Feedback welcome.

2023-07-11 14:23 UTC, wenzeslaus commented
I renamed the module from _v.move.points_ to _v.rast.move_ because it moves vector using raster values (operates on vectors but the big deal is that it is using raster to do the moving).

Tests are included, use pytest, and run locally. Example in the documentation is included, image is generated by a notebook. Pylint mostly passes locally.

2023-07-18 17:46 UTC, petrasovaa commented on src/vector/v.rast.move/v.rast.move.py
> +    """Raised when vector extent is large than region (raster) extent"""
```suggestion
    """Raised when vector extent is larger than region (raster) extent"""
```

2023-07-18 17:52 UTC, petrasovaa requested changes
Looks like it works on lines only? What happens with areas or points? Consider documenting and adding a check.

2023-07-18 18:35 UTC, wenzeslaus commented on src/vector/v.rast.move/v.rast.move.py
> +    """Raised when vector extent is large than region (raster) extent"""
Thanks. Fixed.

2023-07-18 18:38 UTC, wenzeslaus commented
> ...lines only? ...

Right, it works only for lines. Other types would be a reasonable extension. Points are easy to do without this tool.

I added a check which ignore other types and explained the behavior in the documentation. I also added a test which tests for this behavior.

2023-07-18 19:00 UTC, petrasovaa approved these changes

2023-07-19 00:53 UTC, merged